spring:
  datasource:
    url: "jdbc:postgresql:///${spring.cloud.sql.database-name}?${spring.cloud.sql.instance-connection-string}&socketFactory=com.google.cloud.sql.postgres.SocketFactory"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    cloud:
      gcp:
        sql:
          database-name: ${DB_NAME}
          instance-connection-name: ${INSTANCE_CONNECTION_NAME}

logs:
  enabled: ${LOGS_ENABLED:false}